gather-community/gather

Gemfile, Gemfile.lock, app/views/landing/index.html.erb
=> 37 oauth warning

app/mailers/application_mailer.rb, app/mailers/auth_mailer.rb, config/settings.local.yml.example, config/settings.local.yml.travis, spec/mailers/auth_mailer_spec.rb, spec/mailers/general_mailer_spec.rb
=> 76: Add noreply as default reply-to address

app/controllers/users_controller.rb, app/mailers/application_mailer.rb, app/models/user.rb, app/views/users/_full_form.html.erb, config/initializers/devise.rb, db/migrate/20190913130403_add_child_not_confirmed_constraint.rb, db/schema.rb, spec/factories/user_factory.rb, spec/features/people/email_reconfirmation_spec.rb, spec/features/people/user_show_spec.rb, spec/mailers/application_mailer_spec.rb, spec/policies/user_policy_spec.rb, spec/support/policies/permissions.rb
=> 645 children email confirmation

.rubocop.yml, app/decorators/billing/transaction_decorator.rb, app/decorators/meals/meal_decorator.rb, app/decorators/user_decorator.rb, app/helpers/meals_helper.rb, app/helpers/nav_helper.rb, app/helpers/users_helper.rb, app/views/households/index.html.erb, app/views/meals/meals/_menu.html.erb, app/views/meals/meals/_time_cook.html.erb, app/views/meals/meals/index.html.erb, app/views/meals/meals/jobs.html.erb, app/views/meals/meals/show.html.erb, app/views/reservations/reservations/show.html.erb, app/views/users/show.html.erb
=> 272 links change subdomain

app/controllers/concerns/destructible.rb, app/controllers/users_controller.rb, app/mailers/application_mailer.rb, app/models/concerns/deactivatable.rb, app/models/user.rb, config/locales/en/en.yml, db/migrate/20190915192514_update_email_presence_check.rb, db/migrate/20190915200016_add_check_for_email_if_confirmed.rb, db/schema.rb, spec/features/meals/formula_spec.rb, spec/features/people/auth/sign_in_invitation_spec.rb, spec/features/people/user_form_spec.rb, spec/models/user_spec.rb, spec/support/feature_spec_helpers.rb
=> 648 email reclamation

app/controllers/meals/types_controller.rb, app/decorators/meals/type_decorator.rb, app/helpers/nav_helper.rb, app/models/meals/type.rb, app/policies/meals/role_policy.rb, app/policies/meals/type_policy.rb, app/views/accounts/index.html.erb, app/views/meals/formulas/index.html.erb, app/views/meals/roles/index.html.erb, app/views/meals/types/_form.html.erb, app/views/meals/types/edit.html.erb, app/views/meals/types/index.html.erb, app/views/meals/types/new.html.erb, config/locales/en/en.yml, config/locales/en/nav.yml, config/locales/en/simple_form.yml, config/routes.rb, db/migrate/20190928024442_add_deactivated_at_to_meal_types.rb, db/schema.rb, spec/factories/meals/type_factory.rb, spec/features/meals/type_spec.rb, spec/policies/meals/role_policy_spec.rb, spec/policies/meals/type_policy_spec.rb
=> 652 meal types pages

app/controllers/concerns/application_controller/request_preprocessing.rb, app/controllers/landing_controller.rb, app/views/landing/index.html.erb, app/views/layouts/_footer.html.erb, spec/features/subdomain_handling_spec.rb, spec/support/matchers.rb
=> 674 login fail

app/models/utils/nav/customization_parser.rb, spec/models/utils/nav/customization_parser_spec.rb
I created the class and the spec.  Rubocop likes them except that it complains about long lines.  Should I break them up (how?) or just ignore the complaints?
=> Created class and spec for parsing menu customizations

app/assets/javascripts/backbone/views/calendar_link_manager.coffee, app/assets/javascripts/backbone/views/reservation_calendar_view.coffee, app/controllers/reservations/reservations_controller.rb, app/views/reservations/reservations/calendar.html.erb, spec/features/reservations/calendar_spec.rb
=> 185 preserve calendar view

app/assets/javascripts/backbone/views/reservation_calendar_view.coffee, app/assets/stylesheets/local/reservations/calendar.scss
=> 680: Allow day/week/month buttons in mobile calendar view

app/models/community.rb, config/locales/en/custom_fields.yml
Here is the code for the custom menu setting.  I note that lint complains about a line that was already in community.rb
=> Added setting for top menu customization

app/policies/meals/meal_policy.rb, spec/policies/meals/meal_policy_spec.rb
=> 689 fix change formula permission

app/decorators/nav/link_builder.rb, app/models/utils/nav/customization_parser.rb
Here is the work so far.  I decided to put all the customization logic in the CustomizationParser class (should we rename it?).  I am planning to redo the spec so that it tests the new methods of that class, and then the customizations variable can become private.  After that, the feature spec.
Steve
=> 9138 integrate parser

spec/features/nav_menu_spec.rb
Here is a feature spec for the menu customizations.
=> add feature spec

app/controllers/accounts_controller.rb, app/controllers/transactions_controller.rb, app/lenses/date_range_lens.rb, app/models/billing/transaction.rb, app/policies/billing/transaction_policy.rb, app/views/accounts/_transaction_export_form.html.erb, app/views/accounts/index.html.erb, app/views/accounts/show.html.erb, config/locales/en/activerecord.yml, config/locales/en/en.yml, lib/date_range_builder.rb, spec/fixtures/billing/transactions.csv, spec/system/billing/billing_spec.rb, spec/system/meals/report_spec.rb
=> 731 transaction csv adjustments

app/models/user.rb, app/models/utils/generators/admin_generator.rb
=> 772: Remove phone number requirement

app/models/reservations/resource.rb, spec/factories/reservations/resource_factory.rb, spec/models/reservations/resource_spec.rb
=> 749: Fix resource associations on deletion

app/views/meals/meals/form/_workers.html.erb
=> 760: Allow clear head cook

app/views/work_mailer/job_choosing_notice.text.erb, spec/mailers/work_mailer_spec.rb, spec/support/helpers/general_helpers.rb
=> 753: Add period_id to job choosing email

app/models/application_record.rb, app/models/cluster.rb, app/models/meals/formula_role.rb, app/models/utils/data_remover.rb, app/models/utils/generators/main_generator.rb, app/models/utils/generators/people_generator.rb, app/models/utils/generators/work_generator.rb, db/migrate/20201006135423_add_cluster_to_meal_formula_roles.rb, db/schema.rb, spec/factories/work/job_factory.rb, spec/factories/work/period_factory.rb, spec/models/db_spec.rb, spec/models/tenancy_spec.rb, spec/models/utils/generators/main_generator_spec.rb, spec/models/utils/generators/people_generator_spec.rb, spec/models/utils/generators/work_generator_spec.rb, spec/support/contexts/fakes/fake_custom_field_active_record_model.rb, spec/support/contexts/fakes/fake_custom_field_model.rb, spec/support/contexts/fakes/fake_custom_field_model_no_validation.rb
=> 206 more sample data

README.md, app/controllers/groups/groups_controller.rb, app/decorators/groups/mailman/list_decorator.rb, app/views/groups/groups/_form.html.erb, app/views/groups/groups/show.html.erb
=> 758: Add Mailman links to groups#show

app/assets/stylesheets/local/billing/accounts.scss, app/controllers/accounts_controller.rb, app/views/accounts/index.html.erb
=> 785: Add account totals row and sticky header

app/controllers/accounts_controller.rb, app/lenses/billing/account_active_lens.rb, app/models/application_record.rb, app/models/billing/account.rb, app/models/billing/account_manager.rb, app/models/meals/finalizer.rb, config/initializers/listeners.rb, config/locales/en/simple_form.yml, db/migrate/20201014141423_create_missing_accounts.rb, db/schema.rb, spec/factories/billing/account_factory.rb, spec/fixtures/billing/accounts.csv, spec/models/billing/account_csv_exporter_spec.rb, spec/models/billing/account_manager_spec.rb, spec/models/billing/transaction_csv_exporter_spec.rb, spec/models/household_spec.rb, spec/policies/billing/account_policy_spec.rb, spec/policies/billing/statement_policy_spec.rb, spec/policies/billing/transaction_policy_spec.rb, spec/policies/household_policy_spec.rb, spec/support/contexts/policies/permissions.rb, spec/system/billing/billing_spec.rb, spec/system/inactive_spec.rb, spec/system/lens_spec.rb, spec/system/meals/finalize_spec.rb
=> 784 automatic account add

app/mailers/account_mailer.rb, spec/mailers/account_mailer_spec.rb
=> 801: Exclude inactive billers from mail reply to

config/application.rb, lib/console_helper.rb
=> 778: Add console helper

config/environments/production.rb
=> 677: Enable force_ssl

app/models/groups/mailman/list.rb, config/locales/en/simple_form.yml
=> 757: Change list name validation rules and hint

app/assets/javascripts/backbone/views/meal_worker_form_view.coffee, app/controllers/meals/finalize_controller.rb, app/controllers/meals/meals_controller.rb, app/controllers/users_controller.rb, app/models/meals/cost.rb, app/models/meals/finalizer.rb, app/models/meals/meal.rb, app/models/user.rb, app/models/utils/generators/meal_generator.rb, app/policies/meals/meal_policy.rb, app/views/meals/finalize/confirm.html.erb, app/views/meals/finalize/new.html.erb, app/views/meals/meals/form/_expenses.html.erb, app/views/shared/_nested_fields_wrapper.html.erb, config/locales/en/activerecord.yml, config/locales/en/en.yml, db/migrate/20210213021707_add_reimbursee_to_meal_costs.rb, db/schema.rb, spec/factories/meals/cost_factory.rb, spec/models/meals/finalizer_spec.rb, spec/policies/meals/meal_policy_spec.rb, spec/system/meals/crud_spec.rb, spec/system/meals/finalize_spec.rb, spec/system/work/job_spec.rb
=> 802 arbitrary meal expense user

.rubocop.yml, app/controllers/users_controller.rb, app/decorators/user_decorator.rb, app/views/users/_household_select.html.erb, spec/system/people/user_form_spec.rb
=> 741: Allow editing child household

app/controllers/concerns/application_controllable/request_preprocessing.rb, app/controllers/users_controller.rb
=> 715: Make impersonation banner work in other clusters

app/models/groups/mailman/api.rb, app/models/groups/mailman/list_membership.rb, spec/cassettes/groups/mailman/api/create_membership/member.yml, spec/cassettes/groups/mailman/api/create_membership/owner.yml, spec/cassettes/groups/mailman/api/create_user/happy_path.yml, spec/cassettes/groups/mailman/api/create_user/user_exists.yml, spec/cassettes/groups/mailman/api/delete_membership/happy_path.yml, spec/cassettes/groups/mailman/api/delete_user/matching_user.yml, spec/cassettes/groups/mailman/api/delete_user/no_matching_user.yml, spec/cassettes/groups/mailman/api/memberships/for_list/happy_path.yml, spec/cassettes/groups/mailman/api/memberships/for_user/happy_path.yml, spec/cassettes/groups/mailman/api/memberships/for_user/no_matching.yml, spec/cassettes/groups/mailman/api/populate_membership/matching.yml, spec/cassettes/groups/mailman/api/populate_membership/no_matching.yml, spec/cassettes/groups/mailman/api/update_user/email_doesnt_match.yml, spec/cassettes/groups/mailman/api/update_user/email_matches.yml, spec/cassettes/groups/mailman/api/update_user/email_owned_by_other_user.yml, spec/cassettes/groups/mailman/api/user_exists/doesnt_exist.yml, spec/cassettes/groups/mailman/api/user_exists/exists.yml, spec/cassettes/groups/mailman/api/user_id_for_email/doesnt_exist.yml, spec/cassettes/groups/mailman/api/user_id_for_email/exists.yml, spec/models/groups/mailman/api_spec.rb
=> 789 mailman preexist user error

app/decorators/meals/meal_decorator.rb, app/models/meals/meal.rb, app/views/meal_mailer/cancellation_message.text.erb, app/views/meal_mailer/meal_reminder.text.erb, app/views/meal_mailer/normal_message.text.erb, app/views/meal_mailer/role_reminder.text.erb, app/views/meal_mailer/worker_change_notice.text.erb, app/views/meals/meals/_menu.html.erb, app/views/meals/meals/_reimb_form.html.erb, app/views/meals/meals/form/_general.html.erb, config/locales/en/activerecord.yml, config/locales/en/simple_form.yml, spec/models/meals/meal_spec.rb
=> 827: Make meal location optional

app/jobs/groups/mailman/list_sync_job.rb, app/jobs/groups/mailman/membership_sync_job.rb, app/models/groups/mailman/api.rb, spec/cassettes/groups/mailman/api/update_user/email_doesnt_match.yml, spec/cassettes/groups/mailman/api/update_user/email_owned_by_other_user.yml, spec/cassettes/groups/mailman/api/update_user/no_pref_address.yml, spec/cassettes/groups/mailman/integration/all_at_once/create_all.yml, spec/cassettes/groups/mailman/integration/general/add_admin_group_member.yml, spec/cassettes/groups/mailman/integration/general/add_member.yml, spec/cassettes/groups/mailman/integration/general/add_moderate_permission.yml, spec/cassettes/groups/mailman/integration/general/change_member_community_and_ensure_removed_from_everybody_group.yml, spec/cassettes/groups/mailman/integration/general/create_admin_group.yml, spec/cassettes/groups/mailman/integration/general/create_list.yml, spec/cassettes/groups/mailman/integration/general/create_list_for_everybody_group.yml, spec/cassettes/groups/mailman/integration/general/create_user_and_ensure_added.yml, spec/cassettes/groups/mailman/integration/general/deactivate_group.yml, spec/cassettes/groups/mailman/integration/general/deactivate_member.yml, spec/cassettes/groups/mailman/integration/general/destroy_admin_group.yml, spec/cassettes/groups/mailman/integration/general/destroy_list.yml, spec/cassettes/groups/mailman/integration/general/destroy_user.yml, spec/cassettes/groups/mailman/integration/general/remove_member.yml, spec/cassettes/groups/mailman/integration/general/update_user.yml, spec/jobs/groups/mailman/membership_sync_job_spec.rb, spec/models/groups/mailman/api_spec.rb
=> 830 preferred address

app/assets/javascripts/backbone/views/work/period_form_view.coffee, app/models/work/period.rb, app/models/work/period_cloner.rb, app/policies/work/period_policy.rb, app/views/work/periods/_form.html.erb, config/locales/en/activerecord.yml, spec/models/work/period_cloner_spec.rb, spec/policies/work/period_policy_spec.rb, spec/system/work/period_spec.rb
=> 846: Add ability to copy pre-assignments

app/controllers/work/shifts_controller.rb, app/models/work/shift.rb
=> 125: Fix n+1s on shifts page

app/assets/stylesheets/local/meals/summary.scss, app/decorators/meals/meal_decorator.rb, app/decorators/meals/signup_decorator.rb, app/policies/meals/formula_policy.rb, app/policies/meals/signup_policy.rb, app/views/meals/formulas/_form.html.erb, app/views/meals/meals/_signup_form.html.erb, app/views/meals/meals/_signup_read_only.html.erb, app/views/meals/meals/_summary_signups_header.html.erb, app/views/meals/meals/summary.html.erb, config/locales/en/activerecord.yml, config/locales/en/simple_form.yml, db/migrate/20220210143654_add_takeout_to_meal_signups.rb, db/migrate/20220210143926_add_takeout_to_meal_formulas.rb, db/migrate/20220210151908_change_formula_takeout_default_to_true.rb, db/schema.rb, spec/policies/meals/formula_policy_spec.rb, spec/policies/meals/signup_policy_spec.rb
=> 907: Add takeout option for meals

app/controllers/meals/messages_controller.rb, app/views/meals/messages/new.html.erb, config/locales/en/meals.yml, spec/system/meals/cancel_spec.rb
=> 922 meal cancel stronger

app/controllers/concerns/application_controllable/loaders.rb, app/policies/user_policy.rb, app/views/households/index.html.erb
=> 921: Hide inactive users in household views

app/models/calendars/event.rb, spec/support/helpers/system_spec_helpers.rb, spec/system/calendars/events/form_spec.rb, spec/system/people/user_form_spec.rb
=> 937: Fix kind based protocol check bug and add test

app/models/groups/mailman/list.rb, spec/models/groups/mailman/list_spec.rb
=> 941: Respect opt out when determining list memberships via mailman group

app/views/meals/meals/_cost_info.html.erb
=> Fix meal cost page

app/models/groups/group.rb, config/locales/en/simple_form.yml
=> Add Circle group type

app/controllers/application_controller.rb, app/decorators/nav/builder.rb, spec/support/helpers/general_helpers.rb, spec/system/nav_menu_spec.rb
=> 969: Fix nav link subdomains

app/models/meals/import.rb, spec/fixtures/meals/import/with_bom.csv, spec/models/meals/import_spec.rb
=> 973: Handle BOM from Excel CSVs

config/locales/en/privacy_policy.md
Includes language around Google Drive features
Closes #982
=> 982: Privacy policy updates 2023-05

app/models/work/meal_assignment_synchronizer.rb, spec/models/work/meal_assignment_synchronizer_spec.rb
=> 986: Fix sync bug in MealAssignmentSynchronizer

app/assets/stylesheets/global/bootstrap_overrides.scss, app/controllers/groups/mailman/lists_controller.rb, app/decorators/groups/mailman/list_decorator.rb, app/javascript/controllers/index.ts, app/javascript/controllers/partial_list_controller.ts, app/jobs/groups/mailman/membership_sync_job.rb, app/models/groups/group.rb, app/models/groups/mailman/list.rb, app/models/groups/mailman/sync_listener.rb, app/policies/groups/group_policy.rb, app/policies/groups/mailman/list_policy.rb, app/views/groups/groups/_form.html.erb, app/views/groups/groups/show.html.erb, config/routes.rb, db/migrate/20230603114837_add_additional_members_and_additional_senders_to_group_mailman_lists.rb, db/migrate/20230610153051_add_last_synced_at_to_group_mailman_lists.rb, db/schema.rb, spec/jobs/groups/mailman/membership_sync_job_spec.rb, spec/policies/groups/group_policy_spec.rb, spec/policies/groups/mailman/list_policy_spec.rb, spec/system/groups/mailing_list_spec.rb
=> 985 slow group page

app/controllers/meals/meals_controller.rb
=> Show blank assignment slots for meals if the number of signups is less than the role count_per_meal

app/controllers/meals/meals_controller.rb, app/models/community.rb, app/models/meals/import.rb, app/policies/meals/meal_policy.rb, app/views/meals/meals/form/_general.html.erb, config/locales/en/custom_fields.yml, spec/policies/meals/meal_policy_spec.rb
=> 885 invitee settings

app/assets/stylesheets/local/groups/groups.scss
=> Fix opt outs in user list

app/models/user.rb, spec/models/user_spec.rb
=> Fix child age certification to work with non-year birthdays

app/models/groups/group.rb, spec/models/groups/group_spec.rb
=> Make group model nilify mailman list attrib properly

app/models/meals/import.rb, spec/models/meals/import_spec.rb
=> Allow meals imports on calendars in other communities in cluster

app/models/meals/meal.rb
=> Dont count non-persisted items signups collection

config/locales/en/en.yml, spec/mailers/meal_mailer_spec.rb
Attempting a PR from branch to develop (instead of from a cloned repo)
=> Updating for subject line update for meals reminder.

app/assets/stylesheets/global/layout/general.scss, app/decorators/user_decorator.rb
=> 1019: Fix directory width

app/controllers/groups/groups_controller.rb, app/policies/groups/group_policy.rb, spec/policies/groups/group_policy_spec.rb, spec/policies/groups/mailman/list_policy_spec.rb
=> 1023 groups visible cluster

app/views/layouts/_footer.html.erb
=> Rename Accounts in footer to Billing

app/controllers/gdrive/browse_controller.rb, app/models/gdrive/drive_syncer.rb
=> Fix shared drive breadcrumb

app/jobs/gdrive/migration/ingest_job.rb, spec/cassettes/gdrive/migration/ingest_job/file_not_owned_by_consenter.yml, spec/jobs/gdrive/migration/ingest_job_spec.rb
=> Skip files owned by other user

app/mailers/account_mailer.rb, app/mailers/application_mailer.rb, app/mailers/gdrive/migration/mailer.rb, spec/mailers/account_mailer_spec.rb, spec/mailers/application_mailer_spec.rb, spec/mailers/general_mailer_spec.rb
=> Fix mail to inactive users

app/controllers/meals/meals_controller.rb, app/decorators/meals/meal_decorator.rb, app/models/billing/transaction.rb, app/models/meals/finalizer.rb, app/policies/meals/meal_policy.rb, app/views/meals/finalize/complete.html.erb, config/locales/en/en.yml, config/locales/en/meals.yml, config/routes.rb, spec/factories/billing/transaction_factory.rb, spec/factories/meals/meal_factory.rb, spec/models/meals/finalizer_spec.rb, spec/policies/meals/meal_policy_spec.rb, spec/system/meals/finalize_spec.rb
=> Unfinalize meal

app/assets/stylesheets/global/layout/subsubnav.scss, app/helpers/application_helper.rb, app/views/calendars/events/show.html.erb, app/views/groups/groups/show.html.erb, app/views/households/show.html.erb, app/views/layouts/application.html.erb, app/views/meals/formulas/show.html.erb, app/views/meals/meals/show.html.erb, app/views/people/memorials/show.html.erb, app/views/shared/_mobile_back_link.html.erb, app/views/users/show.html.erb, app/views/wiki/pages/show.html.erb, app/views/work/jobs/show.html.erb, app/views/work/periods/show.html.erb, app/views/work/shifts/show.html.erb
Added back links on all relevant show pages:
=> Add back links from show pages on mobile

app/models/billing/statement.rb, spec/jobs/billing/statement_reminder_job_spec.rb, spec/models/billing/statement_spec.rb
=> Dont send reminders for statements with no due date
